# fly.toml app configuration file generated for gac-discord-bot on 2023-07-12T21:23:05-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gac-discord-bot"
primary_region = "iad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
